DROP TABLE IF EXISTS user;
CREATE TABLE user (
    `id` INT(10) AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(30) NOT NULL,
    `password` VARCHAR(160) NOT NULL,
    `email` VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;